### ISSUE TITLE
Cannot Scroll on Fire TV 

### ISSUE THREAD

**Issue by realAllonZ** [kamgurgul/cpu-info#111] opened 2024-02-04 14:15 UTC
Thanks for the wonderful app! It has been very useful on a lot of my devices.

With the latest release it now does not scroll with stock remote or air remote. Any possibility this issue will be fixed?

F-droid
CPU Info 5.2.0
Fire OS 7.6.6.4
Model AFTDCT31

**Comment by kamgurgul** [comment] 2024-02-04 19:50
Probably it is caused by Compose migration :( Is there any available emulator of this this tv?

**Comment by kamgurgul** [comment] 2024-02-05 06:20
Fixed in 5.3.0

**Closed by kamgurgul** 2024-02-05 06:20 UTC
Labels: bug, 5.3.0
